server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: fix-server
  
  # DATABASE CONFIGURATION - COMMENTED OUT FOR INITIAL TESTING
  # datasource:
  #   url: jdbc:postgresql://localhost:5432/fixserver
  #   username: fixserver
  #   password: ${DB_PASSWORD:fixserver}
  #   driver-class-name: org.postgresql.Driver
  #   hikari:
  #     maximum-pool-size: 20
  #     minimum-idle: 5
  #     connection-timeout: 30000
  #     idle-timeout: 600000
  #     max-lifetime: 1800000
  
  # jpa:
  #   hibernate:
  #     ddl-auto: validate
  #   show-sql: false
  #   properties:
  #     hibernate:
  #       dialect: org.hibernate.dialect.PostgreSQL10Dialect
  #       format_sql: true
  #       jdbc:
  #         batch_size: 20
  #       order_inserts: true
  #       order_updates: true
  
  security:
    user:
      name: admin
      password: ${ADMIN_PASSWORD:admin123}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.fixserver: INFO
    org.springframework.security: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/fix-server.log

# FIX Server specific configuration
fix:
  server:
    port: 9878
    max-sessions: 1000
    heartbeat-interval: 30
    session-timeout: 120
    message-buffer-size: 8192
    
    # Netty-based server configuration
    netty:
      enabled: true
      port: 9879
      boss-threads: 1
      worker-threads: 0  # 0 = use default (2 * CPU cores)
      backlog: 128
      receive-buffer-size: 32768  # 32KB
      send-buffer-size: 32768     # 32KB
      keep-alive: true
      tcp-no-delay: true
      reuse-address: true
      session-timeout-seconds: 300    # 5 minutes
      heartbeat-interval-seconds: 30
      max-sessions: 1000
    
  tls:
    enabled: true
    port: 9879
    keystore-path: ${TLS_KEYSTORE_PATH:classpath:keystore.p12}
    keystore-password: ${TLS_KEYSTORE_PASSWORD:changeit}
    truststore-path: ${TLS_TRUSTSTORE_PATH:classpath:truststore.p12}
    truststore-password: ${TLS_TRUSTSTORE_PASSWORD:changeit}
    mutual-auth: true
    protocols: TLSv1.2,TLSv1.3
    cipher-suites: 
      - TLS_AES_256_GCM_SHA384
      - TLS_CHACHA20_POLY1305_SHA256
      - TLS_AES_128_GCM_SHA256
      - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
  
  protocol:
    versions: FIX.4.4,FIXT.1.1
    validate-checksum: true
    validate-sequence-numbers: true
    
  storage:
    retention-days: 90
    archive-batch-size: 1000
    
  monitoring:
    metrics-enabled: true
    health-check-interval: 30
    
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

fix:
  server:
    max-sessions: 10
  tls:
    enabled: false